//
//  TrelloClientCredentials.h
//  ios-trello
//
//  Created by Vince Mansel on 5/24/12.
//  Copyright (c) 2012 waveOcean Software. All rights reserved.
//

#import <Foundation/Foundation.h>
#import "ydefines.h"

YEXTERN NSString * const kTrelloConsumerKey;
YEXTERN NSString * const kTrelloConsumerSecretKey;

/*
 
 Create the file TrelloClientCredentials.m
 
 and add the following, substituting the values generated by Trello "Getting an Application Key" process:
 
 https://trello.com/1/appKey/generate
 
#import "TrelloClientCredentials.h

//YourAppName
NSString * const kTrelloConsumerKey = @"YourConsumerKey";
NSString * const kTrelloConsumerSecretKey = @"YourConsumerSecretKey";
 
*/

